# Generated by Django 4.1.3 on 2022-12-02 19:05

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='images/default.jpg', upload_to='images')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('recommended_by', models.CharField(blank=True, max_length=200, null=True)),
                ('series_name', models.CharField(blank=True, max_length=200, null=True)),
                ('series_number', models.PositiveIntegerField(blank=True, null=True)),
                ('owned', models.BooleanField()),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('read_status', models.CharField(choices=[('NOT_STARTED', 'Not_Started'), ('IN_PROGRESS', 'In_Progress'), ('FINISHED', 'Finished')], default='NOT_STARTED', max_length=12)),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5.0), django.core.validators.MinValueValidator(0.0)])),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_started', models.DateField(blank=True, null=True)),
                ('date_finished', models.DateField(blank=True, null=True)),
                ('times_read', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
